GET http://localhost:4444/grid/status
Accept: */*
Cache-Control: no-cache

###


GET http://localhost:4444/grid/api/proxy?id=:5555
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:4444/grid/session/info?sessionid=777d3add-5122-4067-bb65-b6d5dcf28598
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:4444/wd/hub/session/c6dab5d5-7e68-4003-8068-b0dc27d8c1cc/url
Accept: */*
Cache-Control: no-cache

###
POST http://localhost:4444/wd/hub/session
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "desiredCapabilities": {
    "browserName": "firefox"
  }
}

###


